version: '2.1'
services:
    ###################
    ##    BACKEND    ##
    ###################

    user-db-postgresql:
        image: 'postgres'
        container_name: user-db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=boilerplate
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U postgres']
            interval: 10s
            timeout: 1s
            retries: 10

    xotomicro-back-user-service:
        build:
            context: .
            dockerfile: docker/dockerfile.production
        container_name: xotomicro-back-user-service
        image: xotomicro-back-user-service
        environment:
            - JVM_OPTS=-Xmx512m -Xms512m
            - PROFILE=${PROFILE}
            - ENV=${ENV}

        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8081/actuator/health']
            interval: 10s
            timeout: 1s
            retries: 10
        env_file:
            - .env
